package logica.enums;

/**
 * Enumeration EHora.
 *
 * @author Karla Fernanda Guevara Flores
 * @version 1.0
 * @since 20-11-2019
 */
public enum EHora {
  SIETE, SIETETREINTA, OCHO, OCHOTREINTA, NUEVE, NUEVETREINTA, DIEZ, DIEZTREINTA, ONCE, 
  ONCETREINTA, DOCE, DOCETREINTA, TRECE, TRECETREINTA, CATORCE, CATORCETREINTA, QUINCE, 
  QUINCETREINTA, DIECISEIS, DIECISEISTREINTA, DICIOHO, DICIOCHOTREINTA, DIECINUEVE, 
  DICINUEVETREINTA;
}